### ISSUE TITLE
Hanging build on 4.0-alpha+1 

### ISSUE THREAD

**Issue by serates** [dart-lang/angular#549]
I am working on a branch to upgrade my app to 4.0.0 currently using 4.0.0-alpha+1. Currently pub build results in a hanging build on my application. 

Dart Version: Dart VM version: 1.24.2 (Thu Jun 22 08:42:17 2017) on "macos_x64"
System: Macbook Pro 2.5ghz Core i7, 16GB Memory

Build Log:
```
Loading source assets... 
Loading angular, ares/transformer, transform_sass, test/pub_serve and dart_to_js_script_rewriter transformers... (1.3s)
Loading angular/transform/codegen and angular/transform/reflection_remover transformers... (28.4s)
Building ares... (7:56.7s)^C
```

Pub File: (ares/transformer is a one file transformer that just consumes a json file, the build passes this point)
```
environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: ^4.0.0-alpha+1
  http: '>=0.11.3+13'
  sass: '1.0.0-beta.1'
  stream_transformers: '>=0.3.0 <0.4.0'
  angular_components:
    git:
      url: 'https://github.com/serates/angular_components.git'
      ref: update
  markdown: ^0.11.3
  transform_sass: ^0.2.4
  pwa: ^0.1.7
  built_collection: ^1.5.0
  logging: ^0.11.3

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.2
  test: ^0.12.24
  angular_test: '^1.0.0-beta'
  mockito: ^2.0.2

transformers:
- ares/transformer
- transform_sass
- angular:
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
- angular/transform/reflection_remover:
    $include: test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- $dart2js:
    minify: true

web:
  compiler:
    debug: dartdevc
```

**Comment by matanlurey** [comment]
Ok, let's try some of the following:

1. Remove `resolved_identifiers` (it does not do anything in 4x)
2. Can you remove everything after `- angular:` (`angular/transform`, etc) and try again?

**Comment by matanlurey** [comment]
Here is an example of what our `_tests` package does:

https://github.com/dart-lang/angular/blob/master/_tests/pubspec.yaml#L26

```yaml
transformers:
  - angular:
      entry_points: test/**_test.dart
      $exclude:
          - test/**.template.dart
          - test/core/reflection/reflector_test.dart
          - test/source_gen/template_compiler/test_files/**

  # Allow test to proxy-load files so we can run tests w/ pub serve.
  - test/pub_serve:
      $include: test/**_test.d
```

**Comment by serates** [comment]
No dice unfortunately, i excluded my entire test directory and removed everything below the angular: transformer and the build is still hanging

**Comment by serates** [comment]
Verbose is showing these are the hangers:

```
FINE: [Fine from DeferredRewriter on angular_components|lib/src/utils/numbers/denomination]:
    | Not yet complete after 1:1.0s
FINE: [Fine from DeferredRewriter on angular_components|lib/src/utils/rate_limit_utils/rate_limit_utils]:
    | Not yet complete after 1:1.0s
FINE: [Fine from DeferredRewriter on angular_components|lib/src/utils/strings/string_utils]:
    | Not yet complete after 1:1.0s
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_components|primary]:
    | Not yet complete after 1:1.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/di.dart, angular|lib/experimental.dart
FINE: [Fine from BuilderTransformer: GeneratorBuilder:[TemplateGenerator] on angular|primary]:
    | Not yet complete after 1:1.0s
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_test|primary]:
    | Not yet complete after 1:1.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/src/core/application_ref.dart, angular|lib/src/core/change_detection/constants.dart, angular|lib/src/core/linker/app_view_utils.dart, angular|lib/src/core/linker/view_ref.dart, angular|lib/src/mock/mock_location_strategy.dart, angular|lib/src/platform/location.dart, angular|lib/src/debug/debug_app_view.dart, angular|lib/src/debug/debug_node.dart, angular|lib/di.dart, angular|lib/src/facade/exceptions.dart
```

**Comment by natebosch** [comment]
Odd, it shows it's waiting to read files from `angular`, which it wouldn't be able to read if a `Transformer` is still running on that package, but it doesn't show that a Transformer is still running on angular...

**Comment by nshahan** [comment]
I just published an updated version of the components [0.6.0-alpha+1](https://pub.dartlang.org/packages/angular_components/versions/0.6.0-alpha%2B1).

Can you try it out and see if that makes any difference?

**Comment by serates** [comment]
Still hanging on 0.6.0-alpha+1 here is the verbose log when it seems to enter the loop:

```
FINE: [Fine from DeferredRewriter on angular_components|lib/src/utils/keyboard/keyboard]:
    | Not yet complete after 50.0s
FINE: [Fine from DeferredRewriter on angular_components|lib/src/utils/numbers/denomination]:
    | Not yet complete after 50.0s
FINE: [Fine from DeferredRewriter on angular_components|lib/src/utils/rate_limit_utils/rate_limit_utils]:
    | Not yet complete after 50.0s
FINE: [Fine from DeferredRewriter on angular_components|lib/src/utils/strings/string_utils]:
    | Not yet complete after 50.0s
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_components|primary]:
    | Not yet complete after 50.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/di.dart, angular|lib/experimental.dart
FINE: [Fine from BuilderTransformer: GeneratorBuilder:[TemplateGenerator] on angular|primary]:
    | Not yet complete after 50.0s
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_test|primary]:
    | Not yet complete after 50.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/src/core/application_ref.dart, angular|lib/src/core/change_detection/constants.dart, angular|lib/src/core/linker/app_view_utils.dart, angular|lib/src/core/linker/view_ref.dart, angular|lib/src/mock/mock_location_strategy.dart, angular|lib/src/platform/location.dart, angular|lib/src/debug/debug_app_view.dart, angular|lib/src/debug/debug_node.dart, angular|lib/di.dart, angular|lib/src/facade/exceptions.dart
```

**Comment by nshahan** [comment]
Can you run `pub deps` and post the output? Maybe there is an incompatible version of some dependency that we need to sort out.

**Comment by serates** [comment]
```
ares 0.0.1
|-- angular 4.0.0-alpha+1
|   |-- collection...
|   |-- logging...
|   |-- quiver...
|   |-- analyzer 0.29.11
|   |   |-- args...
|   |   |-- charcode...
|   |   |-- glob...
|   |   |-- html...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- source_span...
|   |   |-- yaml...
|   |   |-- cli_util 0.0.1+2
|   |   |   |-- path...
|   |   |   '-- which 0.1.3
|   |   |       |-- path...
|   |   |       '-- when 0.2.0
|   |   |-- convert 2.0.1
|   |   |   |-- charcode...
|   |   |   '-- typed_data...
|   |   |-- crypto 2.0.1
|   |   |   |-- collection...
|   |   |   '-- convert...
|   |   |-- isolate 1.0.0
|   |   |-- package_config 1.0.1
|   |   |   |-- charcode...
|   |   |   '-- path...
|   |   |-- plugin 0.2.0
|   |   '-- watcher 0.9.7+3
|   |       |-- async...
|   |       |-- collection...
|   |       '-- path...
|   |-- angular_compiler 0.1.1
|   |   |-- args...
|   |   |-- barback...
|   |   |-- build...
|   |   |-- glob...
|   |   |-- logging...
|   |   |-- meta...
|   |   '-- source_gen...
|   |-- barback 0.15.2+11
|   |   |-- async...
|   |   |-- collection...
|   |   |-- path...
|   |   |-- pool...
|   |   |-- source_span...
|   |   '-- stack_trace...
|   |-- build 0.9.3
|   |   |-- analyzer...
|   |   |-- glob...
|   |   |-- logging...
|   |   '-- path...
|   |-- build_barback 0.3.0
|   |   |-- analyzer...
|   |   |-- barback...
|   |   |-- build...
|   |   |-- glob...
|   |   |-- logging...
|   |   '-- code_transformers 0.5.1+3
|   |       |-- analyzer...
|   |       |-- barback...
|   |       |-- cli_util...
|   |       |-- path...
|   |       |-- source_maps...
|   |       '-- source_span...
|   |-- code_builder 1.0.4
|   |   |-- analyzer...
|   |   |-- dart_style...
|   |   |-- func...
|   |   |-- matcher...
|   |   '-- meta...
|   |-- csslib 0.14.0
|   |   |-- args...
|   |   |-- logging...
|   |   |-- path...
|   |   '-- source_span...
|   |-- dart_style 0.2.16
|   |   |-- analyzer...
|   |   |-- args...
|   |   |-- path...
|   |   '-- source_span...
|   |-- func 0.1.1
|   |-- glob 1.1.3
|   |   |-- async...
|   |   |-- collection...
|   |   |-- path...
|   |   '-- string_scanner...
|   |-- html 0.13.2
|   |   |-- csslib...
|   |   |-- source_span...
|   |   '-- utf 0.9.0+3
|   |-- intl 0.15.1
|   |   '-- path...
|   |-- js 0.6.1
|   |-- meta 1.1.0
|   |-- path 1.4.2
|   |-- source_gen 0.6.1+1
|   |   |-- analyzer...
|   |   |-- build...
|   |   |-- collection...
|   |   |-- dart_style...
|   |   |-- path...
|   |   '-- source_span...
|   |-- source_span 1.4.0
|   |   |-- charcode...
|   |   '-- path...
|   |-- stack_trace 1.8.0
|   |   '-- path...
|   '-- tuple 1.0.1
|       '-- quiver_hashcode 1.0.0
|-- angular_components 0.6.0-alpha+1
|   |-- angular...
|   |-- collection...
|   |-- intl...
|   |-- js...
|   |-- logging...
|   |-- meta...
|   |-- quiver...
|   |-- fixnum 0.10.5
|   |-- observable 0.20.4+1
|   |   |-- collection...
|   |   |-- meta...
|   |   '-- quiver...
|   |-- perf_api 0.1.0
|   '-- uuid 0.5.3
|       |-- convert...
|       '-- crypto...
|-- angular_test 1.0.0-beta+4
|   |-- angular...
|   |-- args...
|   |-- collection...
|   |-- func...
|   |-- logging...
|   |-- matcher...
|   |-- meta...
|   |-- path...
|   |-- stack_trace...
|   |-- test...
|   |-- ansicolor 0.0.9
|   '-- pageloader 2.2.6
|       |-- stack_trace...
|       '-- webdriver 1.2.3
|           |-- matcher...
|           |-- path...
|           |-- stack_trace...
|           |-- archive 1.0.31
|           |   |-- args...
|           |   |-- crypto...
|           |   '-- path...
|           '-- unittest 0.11.7
|               '-- stack_trace...
|-- browser 0.10.0+2
|-- built_collection 1.5.0
|   |-- collection 1.14.2
|   '-- quiver 0.25.0
|       '-- matcher...
|-- dart_to_js_script_rewriter 1.0.3
|   |-- barback...
|   '-- html...
|-- http 0.11.3+13
|   |-- collection...
|   |-- path...
|   |-- stack_trace...
|   |-- async 1.13.3
|   |   '-- collection...
|   '-- http_parser 3.1.1
|       |-- charcode...
|       |-- collection...
|       |-- source_span...
|       |-- string_scanner...
|       '-- typed_data 1.1.3
|-- logging 0.11.3+1
|-- markdown 0.11.4
|-- mockito 2.0.2
|   |-- matcher...
|   |-- meta...
|   '-- test...
|-- pwa 0.1.7
|   |-- args...
|   |-- dart_style...
|   |-- func...
|   |-- glob...
|   |-- service_worker 0.0.16
|   |   |-- func...
|   |   '-- js...
|   '-- yaml 2.1.12
|       |-- charcode...
|       |-- collection...
|       |-- source_span...
|       '-- string_scanner...
|-- sass 1.0.0-beta.1
|   |-- collection...
|   |-- path...
|   |-- source_span...
|   |-- stack_trace...
|   |-- tuple...
|   |-- args 0.13.7
|   |-- charcode 1.1.1
|   |-- package_resolver 1.0.2
|   |   |-- collection...
|   |   |-- http...
|   |   |-- package_config...
|   |   '-- path...
|   '-- string_scanner 1.0.2
|       |-- charcode...
|       '-- source_span...
|-- stream_transformers 0.3.0+3
|-- test 0.12.24
|   |-- analyzer...
|   |-- args...
|   |-- async...
|   |-- barback...
|   |-- collection...
|   |-- glob...
|   |-- js...
|   |-- meta...
|   |-- package_resolver...
|   |-- path...
|   |-- source_span...
|   |-- stack_trace...
|   |-- string_scanner...
|   |-- yaml...
|   |-- boolean_selector 1.0.2
|   |   |-- collection...
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- http_multi_server 2.0.3
|   |   '-- async...
|   |-- matcher 0.12.1+1
|   |   '-- stack_trace...
|   |-- node_preamble 1.4.0
|   |-- pool 1.3.1
|   |   |-- async...
|   |   '-- stack_trace...
|   |-- pub_semver 1.3.2
|   |   '-- collection...
|   |-- shelf 0.6.8
|   |   |-- async...
|   |   |-- collection...
|   |   |-- http_parser...
|   |   |-- path...
|   |   |-- stack_trace...
|   |   '-- stream_channel...
|   |-- shelf_packages_handler 1.0.0
|   |   |-- async...
|   |   |-- package_resolver...
|   |   |-- path...
|   |   |-- shelf...
|   |   '-- shelf_static...
|   |-- shelf_static 0.2.5
|   |   |-- convert...
|   |   |-- http_parser...
|   |   |-- path...
|   |   |-- shelf...
|   |   '-- mime 0.9.3
|   |-- shelf_web_socket 0.2.1
|   |   |-- shelf...
|   |   |-- stream_channel...
|   |   '-- web_socket_channel...
|   |-- source_map_stack_trace 1.1.4
|   |   |-- package_resolver...
|   |   |-- path...
|   |   |-- source_maps...
|   |   '-- stack_trace...
|   |-- source_maps 0.10.4
|   |   '-- source_span...
|   |-- stream_channel 1.6.1
|   |   |-- async...
|   |   '-- stack_trace...
|   |-- term_glyph 1.0.0
|   '-- web_socket_channel 1.0.4
|       |-- async...
|       |-- crypto...
|       '-- stream_channel...
'-- transform_sass 0.2.4
    |-- barback...
    |-- package_resolver...
    |-- path...
    '-- sass...
```

**Comment by chalin** [comment]
Hey all, I'm observing the same behavior of a hang on a pub get.

To reproduce it:

- Get the [4-dev branch of site-webdev](https://github.com/dart-lang/site-webdev/tree/4-dev)
- `cd examples/ng/doc/template-syntax`
- `pub get --verbose` ... which eventually loops emitting

```nocode
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_components|primary]:
    | Not yet complete after 3:13.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/di.dart, angular|lib/experimental.dart
FINE: [Fine from BuilderTransformer: GeneratorBuilder:[TemplateGenerator] on angular|primary]:
    | Not yet complete after 3:13.0s
FINE: [Fine from BuilderTransformer: Instance of 'TemplatePlaceholderBuilder' on angular_test|primary]:
    | Not yet complete after 3:13.0s, waiting on input(s) angular|lib/angular.dart, angular|lib/src/core/application_ref.dart, angular|lib/src/core/change_detection/constants.dart, angular|lib/src/core/linker/app_view_utils.dart, angular|lib/src/core/linker/view_ref.dart, angular|lib/src/mock/mock_location_strategy.dart, angular|lib/src/platform/location.dart, angular|lib/src/debug/debug_app_view.dart, angular|lib/src/debug/debug_node.dart, angular|lib/di.dart, angular|lib/src/facade/exceptions.dart
```

cc @kwalrath

**Comment by chalin** [comment]
We have about 30 doc examples, I think that I'm getting this timeout/hanging behavior **only for those examples that have `angular_test` based tests.** E.g., toh-0, toh-1 and template-syntax all hang (and have component tests), but others like `examples/ng/doc/attribute-directives` take longer but don't hang.

**Comment by Nolty** [comment]
If you disable the package angular_test, the problem disappears

**Comment by chalin** [comment]
I can confirm that if I disable E2E tests for all projects with component tests, then the remaining E2E tests pass (e.g., see [this Travis log](https://travis-ci.org/dart-lang/site-webdev/builds/256032765)).

**Comment by serates** [comment]
I can also confirm if i remove angular_test entirely from my pub file (i have to remove the whole package) it now builds.

**Comment by matanlurey** [comment]
Thanks! This at least gives us something to repro

**Comment by matanlurey** [comment]
@serates @chalin Can you folks try using _just_ the `angular` transformer (not `reflection_remover` or `codegen`) and tell me if that works? We hit this problem ourselves (https://github.com/dart-lang/angular/issues/562) and the solution was to just use `angular`.

**Comment by serates** [comment]
@matanlurey I already had removed all that. For me even including angular_test as a dev dependency causes the hang.

**Comment by matanlurey** [comment]
Hmm. And could you try adding this @serates:

(https://github.com/dart-lang/angular/blob/master/angular_test/pubspec.yaml#L38)
```yaml
      $exclude:
          - test/**.template.dart
```

Is it possible to get a copy of your `pub serve` log (i.e. loading ____)?

**Comment by serates** [comment]
@matanlurey  My pubspec excludes everything under the test directory using 

```
$exclude:
   - test/**
```

So even with the above change (i tried anyway) the hang still occurs as long as angular_test is in the dev_dependencies.

Note the hang only occurs on build, i can still use pub serve perfectly fine, above you can see snippets fromt he verbose report of running build, let me know if you want me to export one to a file.

**Comment by chalin** [comment]
@matanlurey - I've tried what you suggested, but pub get still hangs on `examples/ng/doc/template-syntax` [as it did before](https://github.com/dart-lang/angular/issues/549#issuecomment-316977083). Here is what I changed the transformers section to:
```yaml
transformers:
- angular:
    entry_points: web/main.dart
# - angular/transform/reflection_remover:
#     $include: test/**_test.dart
    $exclude:
        - test/**.template.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
```

**Comment by matanlurey** [comment]
@chalin Sorry for the delay on investigating. I'm going to try to investigate with @jakemac53 or @natebosch later this week and see if we can offer any guidance or fixes.

**Comment by zoechi** [comment]
I just run into this issue as well on a new project. After I added `AppComponent` and a new dependency `pub get` was stuck on precompiling with similar output with `-v`. It looks like it keeps kompiling again and again with the same output repeating (just increasing time numbers`)

**Comment by zoechi** [comment]
Removing the `angular_test` dependency fixed it for me

```yml
dev_dependencies:
  # angular_test: '^1.0.0-beta+1'
```

**Comment by matanlurey** [comment]
@zoechi @chalin Does this same issue occur with `angular_components`?

**Comment by chalin** [comment]
Are you asking whether we get the same hanging behavior for an Angular project that depends on `angular_components` (but not `angular_test`)?

**Comment by matanlurey** [comment]
Whether you get the same hanging behavior depending on another package that
depends on Angular rather than just angular_test, yes.

**Comment by zoechi** [comment]
@matanlurey I still have `angular_components` in dependencies. 
I removed all dependencies and added them one-by-one. `angular_test` broke it, any other change didn't have any effect in regard to this problem.

**Comment by chalin** [comment]
Ditto. I'm seeing the same behavior (hanging) for `examples/ng/doc/template-syntax` when I comment out the dev_dependency on `angular_test` but keep `angular_components`.

**Comment by chalin** [comment]
Is an alpha+2 release planned too?

**Comment by chalin** [comment]
Or maybe an new release of angular_test (or both)?

**Comment by alorenzen** [comment]
Yes, we're going to publish new releases of all the packages on Monday. If you're feeling ambitious, you can always try it out from head.

**Comment by matanlurey** [comment]
Yup. It's safe to try against `MASTER` today, we're planning on pushing Monday.

**Comment by matanlurey** [comment]
^

**Comment by serates** [comment]
I can confirm today that the hang is now gone.

**Comment by matanlurey** [comment]
@serates Woohoo! Sorry it took so long.

**Comment by chalin** [comment]
@matanlurey - I'm still getting pub hang on some `pub build` of the ng examples, unless I drop `angular/transform/reflection_remover` from the pubspec. Should I open an issue for this, or maybe one of the changelogs need to be updated to mention this?

**Comment by matanlurey** [comment]
I didn't make the change by 4.0.0+2, but using any transformer but `angular` directly is no longer supported.
