### ISSUE TITLE
`injector.get(tokenDNE, default)` returns empty string instead of default

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#661]
This is a followup to #612 (the fix to which I wasn't able to test before today). The same E2E test is failing:

```nocode
failed - Optional injection displays as expected
      Expected '' to equal 'R.O.U.S.'s? I don't think they exist!'.
```

---

The following code from the AngularDart doc [dependency-injection](https://github.com/dart-lang/site-webdev/tree/4-dev/examples/ng/doc/dependency-injection) example used to work under 4.0.0-alpha (maybe also -beta):

```dart
@Component(
    selector: 'my-injectors',
    template: '''
      <h2>Other Injections</h2>
      <div id="car">{{car.drive()}}</div>
      ...
      <div id="rodent">{{rodent}}</div>''',
    providers: const [...])
class InjectorComponent {
  final Injector _injector;
  Car car;
  ...
  InjectorComponent(this._injector) {
    car = _injector.get(Car);
    ...
  }

  String get rodent =>
    _injector.get(ROUS, "R.O.U.S.'s? I don't think they exist!");
}
```

That is, the default string `"R.O.U.S.'s? I don't think they exist!"` would be displayed for ROUS (which isn't being provided at any level of the app).

Now, in 4.0, `_injector.get(ROUS, "R.O.U.S.'s? I don't think they exist!")` returns the empty string.

cc @kwalrath @kevmoo

**Comment by chalin** [comment]
Btw, the links to the 3.x and current 4.x versions of the app are given below. If you launch the apps, look under "Other Injections". The 3.x app has "R.O.U.S.'s? I don't think they exist!", whereas the 4.x app does not.

- https://webdev-angular3-dartlang-org.firebaseapp.com/examples/ng/doc/dependency-injection
- https://webdev.dartlang.org/examples/dependency-injection/

**Comment by matanlurey** [comment]
This should be fixed in 4.x

**Comment by chalin** [comment]
To reproduce this issue you can use:

```dart
import 'package:angular/angular.dart';

@Component(
  selector: 'my-app',
  template: '''
    injector.get('foo', 'no foo'): {{injector.get('foo', 'no foo') ?? 'null'}}
  ''',
  providers: const [ const Provider('foo', useValue: 42)],
)
class AppComponent {
  final Injector injector;
  AppComponent(this.injector);
}
```

Running yields (as expected):

```nocode
injector.get('foo', 'no foo'): 42
```

Comment out the `providers` and the view becomes:

```nocode
injector.get('foo', 'no foo'): null
```

Let me know if you need any other info.

**Comment by chalin** [comment]
Btw, this seems to be fixed under 5.x, but still fails under 4.x.

**Comment by leonsenft** [comment]
@matanlurey Are we intending to backport a fix for 4.x or should we close this?

**Comment by matanlurey** [comment]
We are not backporting.
